name: CI-post-merge
on:
  push:
    branches:
    - main

jobs:
  update-tag:
    if: "startsWith(github.event.head_commit.message, 'Release v')"
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor

  publish-binary:
    runs-on: ubuntu-latest
    needs:
    - update-tag
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: v${{ needs.update-tag.outputs.new_version }}
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
