# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-file:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
        dry_run: true
    - name: Send greeting
      run: |
        sed -i 's/^World:.*/World: ${{ steps.tag_version.outputs.new_tag }}/' versions
        cat versions
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update Version
        file_pattern: versions
