name: Manual workflow
on:
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "input a new tag name if you want to set non minor versions. (e.g., 0.23.1) (default: bump minor versions)"

jobs:
  update-file:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ github.event.inputs.custom_tag }}
        default_bump: minor
        dry_run: true
    - name: Update versions
      run: |
        sed -i 's/^World:.*/World: ${{ steps.tag_version.outputs.new_tag }}/' versions
        cat versions
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: Release ${{ steps.tag_version.outputs.new_tag }}
        commit-message: Release ${{ steps.tag_version.outputs.new_tag }}
        add-paths: versions
        branch: release-${{ github.event.inputs.custom_tag }}
        reviewers: Ladicle
