name: pr-labeler
on:
  pull_request_target:
    types:
    - opened
    branches:
    - main
    - release-*

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
