on:
  pull_request_target:
    types:
    - opened
    branches:
    - main
    - release-*

permissions:
  pull-requests: write # for labeling pull requests (on: pull_request_target or on: pull_request)

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
