name: CI-post-merge
on:
  push:
    branches:
    - main

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      release_commit: ${{ steps.check.outputs.release_commit }}
    steps:
    - id: check
      run: echo "release_commit=${{ startsWith(github.event.head_commit.message, 'Release v') }}" >> "$GITHUB_OUTPUT"

  non-release:
    if: needs.check-release.outputs.release_commit == false
    needs:
    - check-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: end
      run: |
        echo "This is not a release commit ${{ needs.check-release.outputs.release_commit }}"

  update-tag:
    if: needs.check-release.outputs.release_commit == true
    needs: check-release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract version
      run: |
        echo "This is a release commit: ${{ needs.check-release.outputs.release_commit }}"
        ver=$(echo '${{ github.event.head_commit.message }}'| head -n1 | awk '{print $2}' |sed 's/v//')
        echo "version=${ver}" >> $GITHUB_ENV
    - name: Create release
      uses: softprops/action-gh-release@v2.0.8
      with:
        tag_name: v${{ env.version }}
        generate_release_notes: true
