name: CI-post-merge
on:
  push:
    branches:
    - main
    paths:
    - versions

jobs:
  update-tag:
    if: "startsWith(github.event.head_commit.message, 'Release v')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract version
      run: |
        ver=$(echo '${{ github.event.head_commit.message }}'| head -n1 | awk '{print $2}' |sed 's/v//')
        echo "version=${ver}" >> $GITHUB_ENV
    - name: Push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: v${{ env.version }}
    - name: Create release
      uses: softprops/action-gh-release@v2.0.8
      with:
        tag_name: v${{ env.version }}
        generate_release_notes: true
