name: CI-post-merge
on:
  push:
    branches:
    - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: check release
      run: echo "RELEASE_COMMIT=${{ startsWith(github.event.head_commit.message, 'Release v') }}" >> "$GITHUB_OUTPUT"

  non-release:
    if: ${{ ! steps.chck.outputs.RELEASE_COMMIT }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: end
      run: echo "This is not a release commit"

  update-tag:
    if: ${{ steps.chck.outputs.RELEASE_COMMIT }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Extract version
      run: |
        ver=$(echo '${{ github.event.head_commit.message }}'| head -n1 | awk '{print $2}' |sed 's/v//')
        echo "version=${ver}" >> $GITHUB_ENV
    - name: Create release
      uses: softprops/action-gh-release@v2.0.8
      with:
        tag_name: v${{ env.version }}
        generate_release_notes: true
